### ISSUE TITLE
Mapbox access token in plain text

### ISSUE THREAD

**Issue by tomMoulard** [CodingGarden/next-travel-log#1]
There might be an issue with the following, there is an access token for mapbox accessible. 

https://github.com/CodingGarden/next-travel-log/blob/774f3336f50d2399e600be30238b2e1320d11527/src/components/TravelLogMap.tsx#L42

**Comment by w3cj** [comment]
This is the client map access token that will be exposed whenever I deploy.
BUT it should also be moved to a `.env` file. Thanks for letting me know.

**Comment by w3cj** [comment]
Fixed in a0b0efb6e3ae529bdcdc9bd645b2ab61ccddfebe
